### ISSUE TITLE
Animation seems to be broken

### ISSUE THREAD

**Issue by gedankennebel** [sebastianha/angular-bootstrap-pwgen#1]
Hi, the animation under the password input field seems to do crazy stuff .. have you may noticed anything? I tested in Chrome, Safari and Firefox.

**Comment by sebastianha** [comment]
Hi, I just tested it with a fresh "bower install" and the demo page. Does the demo page also behave weird? I could not reproduce this.

**Comment by gedankennebel** [comment]
Sorry my fault, I forgot the angular-bootstrap-pwgen.css file !! Thanks!
